FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app

COPY server/pom.xml .

RUN mvn dependency:go-offline

COPY server/src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar
COPY certs /app/certs

EXPOSE 8443

ENTRYPOINT ["java", "-jar", "app.jar"]
